import os
import sqlite3

import psycopg
from psycopg.rows import dict_row

from config import DATABASE_PATH


DATABASE_URL = os.environ.get("DATABASE_URL")


class DatabaseConnection:
    """Provide a common database interface for SQLite and PostgreSQL."""

    def __init__(self):
        self.is_postgres = bool(DATABASE_URL)

        if self.is_postgres:
            self.connection = psycopg.connect(
                DATABASE_URL,
                row_factory=dict_row,
            )
        else:
            self.connection = sqlite3.connect(DATABASE_PATH)
            self.connection.row_factory = sqlite3.Row

    def execute(self, query, parameters=()):
        """Execute a SQL query using the correct database placeholder."""

        if self.is_postgres:
            query = query.replace("?", "%s")

        return self.connection.execute(query, parameters)

    def commit(self):
        """Commit the current transaction."""
        self.connection.commit()

    def close(self):
        """Close the database connection."""
        self.connection.close()


def get_connection():
    """Create and return a database connection."""
    return DatabaseConnection()


def init_db():
    """Create the application tables if they do not already exist."""

    connection = get_connection()

    try:
        if connection.is_postgres:

            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS tickets (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    category TEXT NOT NULL,
                    priority TEXT NOT NULL,
                    status TEXT NOT NULL,
                    created_date TEXT NOT NULL,
                    assigned_to TEXT NOT NULL
                )
                """
            )

            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    created_date TEXT NOT NULL,
                    role TEXT NOT NULL DEFAULT 'User'
                )
                """
            )

            columns = connection.execute(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = 'users'
                """
            ).fetchall()

            column_names = [column["column_name"] for column in columns]

            if "role" not in column_names:
                connection.execute(
                    """
                    ALTER TABLE users
                    ADD COLUMN role TEXT NOT NULL DEFAULT 'User'
                    """
                )

        else:

            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS tickets (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    category TEXT NOT NULL,
                    priority TEXT NOT NULL,
                    status TEXT NOT NULL,
                    created_date TEXT NOT NULL,
                    assigned_to TEXT NOT NULL
                )
                """
            )

            connection.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    username TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    created_date TEXT NOT NULL,
                    role TEXT NOT NULL DEFAULT 'User'
                )
                """
            )

            columns = connection.execute(
                "PRAGMA table_info(users)"
            ).fetchall()

            column_names = [column["name"] for column in columns]

            if "role" not in column_names:
                connection.execute(
                    """
                    ALTER TABLE users
                    ADD COLUMN role TEXT NOT NULL DEFAULT 'User'
                    """
                )

        connection.commit()

    finally:
        connection.close()